"""
Export a plain chronological reading-history snapshot for the canon_framework
ChatGPT project (data/external_models/canon_framework/reading_history.md).

This is raw data only -- no tier/verdict judgments. The framework itself
(05_decision_logic.md) is what checks recent reads against the reading-diet
ratio; this script just gives it something current to check against.
Re-run and re-upload to ChatGPT whenever you want the project's picture of
your reading history refreshed -- it's a manual, on-demand snapshot, not a
synced source.

Usage:
  python scripts/export_reading_history.py
"""
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent.parent))

from processors.books import load_books_cache, read_jsonl

DATA_DIR = Path(__file__).parent.parent / "data"
OUT_PATH = DATA_DIR / "external_models" / "canon_framework" / "reading_history.md"


def sort_key(entry):
    return entry.get("date_read") or entry.get("date_added") or ""


def main():
    books_by_id = load_books_cache(DATA_DIR / "books.jsonl")
    shelf_entries = read_jsonl(DATA_DIR / "shelf_entries.jsonl")
    reviews_by_id = {r["review_id"]: r for r in read_jsonl(DATA_DIR / "reviews.jsonl")}

    if not books_by_id or not shelf_entries:
        print("No data yet. Run: python scripts/ingest_goodreads.py")
        sys.exit(1)

    read_entries = sorted(
        (e for e in shelf_entries if e.get("shelf") == "read" and e.get("date_read")),
        key=sort_key,
    )
    dnf_entries = [e for e in shelf_entries if e.get("shelf") == "did-not-finish"]

    lines = [
        "# Reading History (raw export, no verdicts)",
        "",
        f"Generated by `scripts/export_reading_history.py`. {len(read_entries)} books "
        "finished, chronological. This file carries no tier/verdict judgments -- that's "
        "the canon_framework's job; this is just current source data for it.",
        "",
        "## Finished, chronological (oldest first)",
        "",
    ]

    for i, entry in enumerate(read_entries, 1):
        book = books_by_id.get(entry.get("book_id"), {})
        review = reviews_by_id.get(entry.get("review_id"))
        title = entry.get("title") or book.get("title") or "Unknown title"
        authors = ", ".join(book.get("authors", [])) or "Unknown author"
        pages = book.get("num_pages")
        genres = ", ".join(book.get("genres", [])[:5])
        date_read = entry.get("date_read")

        line = f"{i}. **{title}** -- {authors}"
        if pages:
            line += f" -- {pages}p"
        line += f" -- finished {date_read}"
        if genres:
            line += f" -- _{genres}_"
        lines.append(line)

        if review and review.get("rating"):
            stars = "★" * review["rating"] + "☆" * (5 - review["rating"])
            lines.append(f"   {stars}")
        if review and review.get("review_text"):
            text = review["review_text"].strip().replace("\n", " ")
            if len(text) > 300:
                text = text[:300].rsplit(" ", 1)[0] + "..."
            lines.append(f"   > {text}")
        lines.append("")

    if dnf_entries:
        lines.append("## Did-not-finish shelf")
        lines.append("")
        for entry in dnf_entries:
            book = books_by_id.get(entry.get("book_id"), {})
            title = entry.get("title") or book.get("title") or "Unknown title"
            authors = ", ".join(book.get("authors", [])) or "Unknown author"
            review = reviews_by_id.get(entry.get("review_id"))
            line = f"- **{title}** -- {authors}"
            lines.append(line)
            if review and review.get("review_text"):
                text = review["review_text"].strip().replace("\n", " ")
                if len(text) > 200:
                    text = text[:200].rsplit(" ", 1)[0] + "..."
                lines.append(f"  > {text}")
        lines.append("")

    OUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    OUT_PATH.write_text("\n".join(lines))
    print(f"Wrote {len(read_entries)} finished books ({len(dnf_entries)} DNF) to {OUT_PATH}")


if __name__ == "__main__":
    main()
